// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWc5IjxtRGMx7CM9Nlt-VOUlzfVHcqL9Q',
    appId: '1:551715176593:web:bba1fa0351ad33775e7f30',
    messagingSenderId: '551715176593',
    projectId: 'musicstreaming-b7a7b',
    authDomain: 'musicstreaming-b7a7b.firebaseapp.com',
    storageBucket: 'musicstreaming-b7a7b.appspot.com',
    measurementId: 'G-1Z7BNRZW0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOtY0ei8-a8wXOCsggxVkQcmxXxfAZYhk',
    appId: '1:551715176593:android:63633e7a58bdc7835e7f30',
    messagingSenderId: '551715176593',
    projectId: 'musicstreaming-b7a7b',
    storageBucket: 'musicstreaming-b7a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgtMbewWedr6FZYLjif9SiRIBPgaFwWk',
    appId: '1:551715176593:ios:13209d47205ff98b5e7f30',
    messagingSenderId: '551715176593',
    projectId: 'musicstreaming-b7a7b',
    storageBucket: 'musicstreaming-b7a7b.appspot.com',
    iosBundleId: 'com.ynov.musicstreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqgtMbewWedr6FZYLjif9SiRIBPgaFwWk',
    appId: '1:551715176593:ios:a24a50146b3db70a5e7f30',
    messagingSenderId: '551715176593',
    projectId: 'musicstreaming-b7a7b',
    storageBucket: 'musicstreaming-b7a7b.appspot.com',
    iosBundleId: 'com.ynov.musicstreaming.RunnerTests',
  );
}
